{% set name = "optkit" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_url: ../
  #https://github.com/bungun/optkit.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  skip: True  # [win]

requirements:
  build:
   - python
   - setuptools
  run:
   - python
   - numpy
   - scipy
   - six

about:
  home: https://github.com/bungun/optkit
  license: TBD
  summary: 'CPU/GPU optimization library and Python interface'
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - bungun