from optkit.tests.linsys import test_linsys
from optkit.tests.prox import test_prox
from optkit.tests.proj import test_projector
from optkit.tests.equil import test_equil
from optkit.tests.normproj import test_normalizedprojector
from optkit.tests.blocksplitting import test_blocksplitting
from optkit.tests.pogs import test_pogs
from optkit.tests.c_equil import test_cequil
from optkit.tests.c_proj import test_cproj
from optkit.tests.c_pogs import test_cpogs
from optkit.tests.c_store import test_cstore